// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.13/01       [396545]
Creator        : ayagil
Date           : Fri Jan 26 14:41:24 2018
Host           : Darwin glut-2.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov 9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
Dir            : /Users/ayagil/Dropbox/UCSD-Adler/MVA stuff/mytut
Training events: 686
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "8" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
BPDIAS                        BPDIAS                        BPDIAS                        BPDIAS                        units                             'F'    [14,125]
CREATN                        CREATN                        CREATN                        CREATN                        units                             'F'    [0.0900000035763,14.4399995804]
BUN                           BUN                           BUN                           BUN                           units                             'F'    [3,116]
HGB                           HGB                           HGB                           HGB                           units                             'F'    [5.90000009537,18.2999992371]
WBC                           WBC                           WBC                           WBC                           units                             'F'    [0.10000000149,70.1999969482]
PLT                           PLT                           PLT                           PLT                           units                             'F'    [7,651]
ALB                           ALB                           ALB                           ALB                           units                             'F'    [1.10000002384,5.09999990463]
RDW                           RDW                           RDW                           RDW                           units                             'F'    [10.6999998093,31.2999992371]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "BPDIAS", "CREATN", "BUN", "HGB", "WBC", "PLT", "ALB", "RDW" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.66827392872532);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 62.1111, 1, 1, 0.766454,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0953603,-99) , 
5, 127.556, 1, 0, 0.206371,-99) , 
6, 3.32222, 1, 0, 0.496796,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.457815);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 54.2222, 1, 1, 0.625745,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0818711,-99) , 
0, 60.1111, 1, 0, 0.198562,-99) , 
6, 3.32222, 1, 0, 0.426764,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.390371);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 46, 1, 1, 0.891456,-99) , 
NN(
0, 
0, 
-1, 3.43333, 1, -1, 0.352555,-99) , 
0, 51, 1, 0, 0.437352,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.583876);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.750359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261809,-99) , 
0, 80.4444, 1, 0, 0.674751,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153421,-99) , 
0, 60.1111, 1, 0, 0.216151,-99) , 
6, 3.54444, 1, 0, 0.498379,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.524964);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 7.98889, 0, 1, 0.835565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.779759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303902,-99) , 
4, 15.8333, 0, 0, 0.366419,-99) , 
6, 2.83333, 1, 0, 0.489376,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.458959);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372052,-99) , 
5, 200.667, 1, 0, 0.564964,-99) , 
NN(
0, 
0, 
-1, 3.98889, 1, -1, 0.215129,-99) , 
6, 3.7, 1, 0, 0.438136,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.320125);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 78.3333, 0, 1, 0.615916,-99) , 
NN(
0, 
0, 
-1, 7.07778, 0, -1, 0.130434,-99) , 
6, 3.93333, 1, 0, 0.541475,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.501482);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.65556, 1, 1, 0.710724,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.775066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257026,-99) , 
0, 45.3333, 1, 0, 0.308245,-99) , 
3, 10.0333, 1, 0, 0.473063,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.324425);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 43.3333, 1, 1, 0.754368,-99) , 
NN(
0, 
0, 
-1, 4.05556, 1, -1, 0.384951,-99) , 
0, 58.4444, 1, 0, 0.495528,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.378978);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 66, 1, 1, 0.750591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.842493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346617,-99) , 
4, 22.7222, 0, 0, 0.377524,-99) , 
6, 2.7, 1, 0, 0.446266,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.329625);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.78889, 1, 1, 0.610996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280835,-99) , 
6, 2.76667, 1, 0, 0.334288,-99) , 
2, 25.6667, 0, 0, 0.440531,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.220137);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 12.8333, 0, 1, 0.573423,-99) , 
NN(
0, 
0, 
-1, 25.6667, 0, -1, 0.0793477,-99) , 
6, 4.13333, 1, 0, 0.52376,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.365618);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.872164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472287,-99) , 
3, 9.56667, 1, 0, 0.654042,-99) , 
NN(
0, 
0, 
-1, 14.3, 0, -1, 0.330949,-99) , 
0, 58.8889, 1, 0, 0.458829,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.242332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.187864,-99) , 
7, 13.7889, 0, 0, 0.494966,-99) , 
NN(
0, 
0, 
-1, 212.444, 1, -1, 0.0258829,-99) , 
0, 84, 1, 0, 0.462352,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.389072);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482894,-99) , 
4, 8.67778, 0, 0, 0.638248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0874465,-99) , 
4, 4.57778, 1, 0, 0.222474,-99) , 
6, 3.8, 1, 0, 0.569124,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.274252);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.78889, 1, 1, 0.641656,-99) , 
NN(
0, 
0, 
-1, 7.33333, 0, -1, 0.378117,-99) , 
5, 209.667, 1, 0, 0.536793,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.137545);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240248,-99) , 
5, 78.5556, 0, 0, 0.482255,-99) , 
0, 40.2222, 1, 0, 0.513448,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.288481);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.55556, 1, 1, 0.745575,-99) , 
NN(
0, 
0, 
-1, 241.111, 1, -1, 0.39145,-99) , 
6, 2.83333, 1, 0, 0.47368,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.370716);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 9.63333, 1, 1, 0.708568,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233305,-99) , 
6, 3.21111, 1, 0, 0.3895,-99) , 
0, 58.4444, 1, 0, 0.472815,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.291299);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.68889, 1, 1, 0.785221,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381185,-99) , 
0, 36.4444, 1, 0, 0.398822,-99) , 
2, 65.7778, 0, 0, 0.428599,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.313367);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 15.1667, 0, 1, 0.765189,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336766,-99) , 
5, 134.667, 1, 0, 0.426721,-99) , 
5, 369.667, 0, 0, 0.470479,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.294089);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.30333, 1, 1, 0.918031,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319657,-99) , 
2, 15.3333, 0, 0, 0.512862,-99) , 
0, 45.3333, 1, 0, 0.560542,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.32939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.33333, 1, 1, 0.634054,-99) , 
NN(
0, 
0, 
-1, 9.31111, 0, -1, 0.267764,-99) , 
7, 14.4556, 0, 0, 0.541037,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.181871);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.868361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458368,-99) , 
3, 9.35556, 1, 0, 0.695692,-99) , 
NN(
0, 
0, 
-1, 3.05556, 0, -1, 0.432792,-99) , 
6, 2.76667, 1, 0, 0.469342,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.259071);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 18.8889, 0, 1, 0.833984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315878,-99) , 
4, 7.34444, 0, 0, 0.447533,-99) , 
4, 16.5889, 0, 0, 0.484773,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.288882);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 44.6667, 1, 1, 0.571444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167074,-99) , 
6, 3.03333, 1, 0, 0.241911,-99) , 
7, 14.1444, 0, 0, 0.474966,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.301459);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473945,-99) , 
7, 15.4444, 1, 0, 0.61174,-99) , 
NN(
0, 
0, 
-1, 13.9333, 0, -1, 0.262452,-99) , 
6, 3.93333, 1, 0, 0.568839,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.453251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.802924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 14.1111, 0, 0, 0.689038,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368283,-99) , 
0, 43.3333, 1, 0, 0.412757,-99) , 
6, 3.9, 0, 0, 0.499899,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.383339);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 119.333, 0, 1, 0.702888,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.122333,-99) , 
0, 74, 1, 0, 0.443814,-99) , 
5, 148.333, 1, 0, 0.547958,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.193613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 68, 1, 1, 0.782851,-99) , 
NN(
0, 
0, 
-1, 3.92222, 1, -1, 0.42783,-99) , 
6, 2.7, 1, 0, 0.467337,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.411449);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.776897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400526,-99) , 
3, 9.66667, 0, 0, 0.654874,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.890039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333421,-99) , 
0, 47.3333, 1, 0, 0.363348,-99) , 
5, 138.444, 1, 0, 0.479569,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.370056);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479238,-99) , 
1, 1.49556, 1, 0, 0.641088,-99) , 
NN(
0, 
0, 
-1, 205.667, 0, -1, 0.233117,-99) , 
6, 3.8, 1, 0, 0.560128,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.325079);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394175,-99) , 
5, 305.667, 1, 0, 0.585694,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.192008,-99) , 
0, 59, 1, 0, 0.336899,-99) , 
4, 5.87778, 0, 0, 0.533397,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.357314);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 123.667, 0, 1, 0.908377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374842,-99) , 
2, 40.6667, 0, 0, 0.449738,-99) , 
3, 7.48889, 1, 0, 0.492322,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.13446);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.791269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49362,-99) , 
7, 13.3778, 1, 0, 0.537628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 14.6111, 1, 0, 0.515807,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.26298);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.679184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451577,-99) , 
0, 61.1111, 1, 0, 0.552765,-99) , 
NN(
0, 
0, 
-1, 13.9333, 0, -1, 0.11319,-99) , 
6, 4.05556, 1, 0, 0.518282,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.295199);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.73333, 0, 1, 0.823491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247358,-99) , 
4, 6.94444, 0, 0, 0.429181,-99) , 
4, 15.6778, 0, 0, 0.495026,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.235556);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.64444, 0, 1, 0.782307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443389,-99) , 
0, 34.8889, 1, 0, 0.465931,-99) , 
7, 18.1667, 0, 0, 0.528493,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.145692);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 17.0333, 0, 1, 0.554711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 14.6333, 1, 0, 0.532757,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0918067);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 11.9667, 0, 1, 0.772487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.172241,-99) , 
3, 7.63333, 0, 0, 0.47521,-99) , 
6, 2.37778, 1, 0, 0.498379,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.456164);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.76919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314852,-99) , 
3, 12.2333, 1, 0, 0.689868,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.262556,-99) , 
2, 26.4444, 0, 0, 0.374719,-99) , 
0, 58.4444, 1, 0, 0.48494,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.148425);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.913869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479401,-99) , 
0, 70.6667, 1, 0, 0.709627,-99) , 
NN(
0, 
0, 
-1, 15.3333, 1, -1, 0.456425,-99) , 
6, 2.78889, 1, 0, 0.497525,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.350817);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.871329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453952,-99) , 
7, 15.1556, 1, 0, 0.726318,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.914123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422272,-99) , 
0, 49, 1, 0, 0.472578,-99) , 
2, 15.5556, 1, 0, 0.570504,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.255495);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.745988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487722,-99) , 
0, 58.6667, 1, 0, 0.669623,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46933,-99) , 
1, 1.68444, 0, 0, 0.53372,-99) , 
0, 64.4444, 1, 0, 0.597136,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.253973);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 15.1889, 0, 1, 0.590424,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308825,-99) , 
4, 7, 0, 0, 0.436224,-99) , 
4, 8.81111, 0, 0, 0.503295,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.173425);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.738826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4952,-99) , 
3, 13.1667, 0, 0, 0.549331,-99) , 
NN(
0, 
0, 
-1, 58.3333, 1, -1, 0.155955,-99) , 
7, 13.7889, 0, 0, 0.509539,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.296132);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381319,-99) , 
7, 13.7889, 0, 0, 0.586239,-99) , 
NN(
0, 
0, 
-1, 245.556, 0, -1, 0.233965,-99) , 
6, 3.93333, 1, 0, 0.553852,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.373189);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.760263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471611,-99) , 
4, 8.36667, 1, 0, 0.604208,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.181784,-99) , 
7, 13.1, 1, 0, 0.262004,-99) , 
6, 3.54444, 1, 0, 0.504132,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.295411);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 15.9889, 0, 1, 0.633007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.042902,-99) , 
1, 8.69111, 1, 0, 0.613804,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.237685);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 9.83333, 1, 1, 0.589922,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287056,-99) , 
6, 4.23333, 0, 0, 0.369801,-99) , 
7, 13.9222, 0, 0, 0.539242,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.274131);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 390.778, 0, 1, 0.822436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182824,-99) , 
4, 11.2333, 1, 0, 0.437199,-99) , 
4, 16.9, 0, 0, 0.50319,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.210984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 56.3333, 1, 1, 0.755802,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434112,-99) , 
4, 4.14444, 1, 0, 0.475623,-99) , 
4, 17.1667, 0, 0, 0.495064,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.279534);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 22.6667, 1, 1, 0.73038,-99) , 
NN(
0, 
0, 
-1, 274.889, 1, -1, 0.372538,-99) , 
4, 18.0778, 0, 0, 0.403047,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.183339);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352278,-99) , 
2, 53.2222, 1, 0, 0.545575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.158332,-99) , 
3, 7.27778, 0, 0, 0.530858,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.341311);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.08889, 1, 1, 0.864713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374149,-99) , 
7, 13.8778, 1, 0, 0.447306,-99) , 
2, 65.7778, 0, 0, 0.486643,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.29527);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 32, 0, 1, 0.829778,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.956865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388272,-99) , 
7, 12.3556, 1, 0, 0.416122,-99) , 
4, 16.7444, 0, 0, 0.446675,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.328579);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 72, 1, 1, 0.96522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0979964,-99) , 
6, 4.1, 1, 0, 0.513159,-99) , 
6, 2.41111, 1, 0, 0.58209,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.332922);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.94829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388584,-99) , 
1, 1.08111, 0, 0, 0.70795,-99) , 
NN(
0, 
0, 
-1, 122.222, 0, -1, 0.362506,-99) , 
6, 2.45556, 1, 0, 0.410491,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.268816);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461935,-99) , 
6, 3.32222, 1, 0, 0.590543,-99) , 
NN(
0, 
0, 
-1, 3.54444, 1, -1, 0.354956,-99) , 
5, 230.333, 1, 0, 0.513783,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0988485);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 61.3333, 1, 1, 0.827332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.107562,-99) , 
7, 12.6778, 0, 0, 0.506203,-99) , 
4, 16.3667, 0, 0, 0.528707,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.265603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323995,-99) , 
2, 18.2222, 0, 0, 0.644156,-99) , 
NN(
0, 
0, 
-1, 18.9333, 1, -1, 0.438548,-99) , 
4, 10.2, 0, 0, 0.529241,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.264416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.825652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495743,-99) , 
2, 47.1111, 1, 0, 0.736718,-99) , 
NN(
0, 
0, 
-1, 8.33333, 1, 1, 0.566774,-99) , 
2, 27.6667, 0, 0, 0.628379,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.366163);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.692076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255503,-99) , 
4, 6.65556, 0, 0, 0.64604,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.79268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366977,-99) , 
1, 3.06222, 0, 0, 0.404458,-99) , 
5, 183, 0, 0, 0.539469,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.292105);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293897,-99) , 
2, 14.6667, 0, 0, 0.511454,-99) , 
NN(
0, 
0, 
-1, 12.6333, 1, -1, 0.331035,-99) , 
6, 3.32222, 1, 0, 0.434788,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.253103);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.862788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45706,-99) , 
7, 18.4333, 0, 0, 0.515848,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153336,-99) , 
5, 412.111, 0, 0, 0.249329,-99) , 
5, 288.556, 1, 0, 0.460245,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.225391);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 9.7, 1, 1, 0.693006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307816,-99) , 
2, 14.3333, 0, 0, 0.451128,-99) , 
0, 58.4444, 1, 0, 0.529543,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.339973);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.814923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474324,-99) , 
6, 2.93333, 1, 0, 0.602404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308867,-99) , 
5, 139.111, 1, 0, 0.392934,-99) , 
3, 9.83333, 1, 0, 0.481008,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.27794);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.24444, 0, 1, 0.617516,-99) , 
NN(
0, 
0, 
-1, 72, 1, -1, 0.26733,-99) , 
2, 41.3333, 1, 0, 0.562831,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.318408);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404187,-99) , 
3, 11.9444, 0, 0, 0.493908,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 212, 1, 0, 0.151922,-99) , 
0, 81.3333, 1, 0, 0.443593,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.164411);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.22333, 0, 1, 0.922482,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270045,-99) , 
5, 274.889, 1, 0, 0.448458,-99) , 
6, 2.43333, 1, 0, 0.48042,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.345958);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373862,-99) , 
5, 277.667, 1, 0, 0.61445,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.095627,-99) , 
5, 232.111, 0, 0, 0.372649,-99) , 
0, 76.5556, 1, 0, 0.576394,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.257102);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451708,-99) , 
0, 73.8889, 1, 0, 0.696323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.262676,-99) , 
6, 4.16667, 1, 0, 0.500934,-99) , 
5, 241.667, 0, 0, 0.581414,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.239285);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.797611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484215,-99) , 
7, 16.6778, 0, 0, 0.600376,-99) , 
NN(
0, 
0, 
-1, 3.47778, 1, -1, 0.384583,-99) , 
2, 27.6667, 0, 0, 0.47366,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.298379);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434644,-99) , 
2, 44.3333, 1, 0, 0.809713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.79717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406768,-99) , 
4, 4.22222, 1, 0, 0.448705,-99) , 
1, 2.86333, 0, 0, 0.493762,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.275191);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 15.7333, 1, 1, 0.832103,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328226,-99) , 
5, 139, 0, 0, 0.461113,-99) , 
4, 12.6333, 0, 0, 0.543422,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.364801);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.83333, 0, 1, 0.620864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0948839,-99) , 
6, 2.7, 1, 0, 0.183072,-99) , 
4, 5.65556, 0, 0, 0.520443,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.433558);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.13333, 1, 1, 0.913505,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.823566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341267,-99) , 
5, 55.8889, 1, 0, 0.38591,-99) , 
5, 448, 0, 0, 0.452334,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.175969);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 36.4444, 1, 1, 0.53586,-99) , 
NN(
0, 
0, 
-1, 66.7778, 1, -1, 0.213134,-99) , 
7, 14.1444, 0, 0, 0.469996,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.233504);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 229.667, 1, 1, 0.793247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218408,-99) , 
4, 6.14444, 0, 0, 0.464739,-99) , 
6, 2.76667, 1, 0, 0.523117,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.512226);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284649,-99) , 
5, 235, 1, 0, 0.62516,-99) , 
NN(
0, 
0, 
-1, 2.8, 1, -1, 0.247037,-99) , 
0, 66.7778, 1, 0, 0.437405,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.342172);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467794,-99) , 
6, 2.04444, 0, 0, 0.731143,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313013,-99) , 
0, 58.8889, 1, 0, 0.395322,-99) , 
6, 2.63333, 1, 0, 0.452513,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.315542);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.970723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430969,-99) , 
4, 7.51111, 0, 0, 0.739664,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376291,-99) , 
2, 64.6667, 0, 0, 0.398109,-99) , 
6, 2.53333, 1, 0, 0.441236,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.183841);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.07778, 1, 1, 0.57571,-99) , 
NN(
0, 
0, 
-1, 3.58889, 0, -1, 0.39515,-99) , 
6, 3.32222, 1, 0, 0.481599,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.251383);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.9083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 3.3, 1, 0, 0.760349,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.845999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480792,-99) , 
5, 45.3333, 1, 0, 0.518672,-99) , 
5, 296.778, 0, 0, 0.564382,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.25616);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 17.6333, 0, 1, 0.649357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0593789,-99) , 
6, 3.8, 1, 0, 0.470355,-99) , 
1, 1.31778, 1, 0, 0.591998,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.187439);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 16.4889, 1, 1, 0.871269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 15.1556, 1, 0, 0.513187,-99) , 
6, 2.43333, 1, 0, 0.55883,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.42722);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.779781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384244,-99) , 
2, 36.3333, 1, 0, 0.673277,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332826,-99) , 
2, 12.8889, 1, 0, 0.424821,-99) , 
6, 3.11111, 1, 0, 0.541613,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.250749);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 87.8889, 1, 0, 0.58469,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0793413,-99) , 
5, 265.667, 1, 0, 0.374101,-99) , 
3, 8.81111, 0, 0, 0.544479,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.386804);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.950257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.267747,-99) , 
2, 49.1111, 1, 0, 0.63817,-99) , 
NN(
0, 
0, 
-1, 122.111, 0, -1, 0.363043,-99) , 
2, 40.6667, 0, 0, 0.42402,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.290729);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.869511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236891,-99) , 
7, 14.6778, 0, 0, 0.756984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422294,-99) , 
0, 38.6667, 1, 0, 0.442611,-99) , 
2, 40, 0, 0, 0.502123,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.29018);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405767,-99) , 
7, 14.3333, 0, 0, 0.575623,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.723865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363478,-99) , 
6, 2.44444, 1, 0, 0.409807,-99) , 
6, 3.54444, 0, 0, 0.476856,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.279496);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 42.4444, 1, 1, 0.849114,-99) , 
NN(
0, 
0, 
-1, 3.43333, 1, -1, 0.392937,-99) , 
0, 47.3333, 1, 0, 0.447885,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.196602);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.83333, 0, 1, 0.826098,-99) , 
NN(
0, 
0, 
-1, 12.7889, 1, -1, 0.429545,-99) , 
6, 2.33333, 1, 0, 0.470804,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.260442);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.02222, 0, 1, 0.837819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.81557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441775,-99) , 
0, 45.6667, 1, 0, 0.469949,-99) , 
6, 2.76667, 1, 0, 0.540263,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.320192);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 10.9, 1, 1, 0.799263,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.782242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431802,-99) , 
6, 2.73333, 1, 0, 0.483279,-99) , 
0, 75.6667, 0, 0, 0.570656,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.273178);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.960262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338156,-99) , 
0, 74, 0, 0, 0.826919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.902281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477809,-99) , 
7, 20.8111, 0, 0, 0.523176,-99) , 
6, 4.16667, 0, 0, 0.587366,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.352659);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.837152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3993,-99) , 
5, 154.333, 1, 0, 0.748866,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351751,-99) , 
5, 227.444, 0, 0, 0.47236,-99) , 
4, 5.47778, 1, 0, 0.537646,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.29982);
  fForest.push_back( 
NN(
0, 
0, 
-1, 21.5667, 0, 1, 0.645574,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.352366);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 17.2, 0, 1, 0.633797,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.110321,-99) , 
6, 2.83333, 1, 0, 0.349135,-99) , 
5, 283.667, 1, 0, 0.591385,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.425912);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.810035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458404,-99) , 
5, 183, 1, 0, 0.671292,-99) , 
NN(
0, 
0, 
-1, 11.4444, 1, -1, 0.301278,-99) , 
0, 60, 1, 0, 0.454058,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.282944);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3209,-99) , 
5, 344.556, 1, 0, 0.704967,-99) , 
NN(
0, 
0, 
-1, 1.46889, 1, -1, 0.427427,-99) , 
6, 3.15556, 1, 0, 0.523091,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.330406);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 20, 1, 1, 0.71784,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341601,-99) , 
0, 69.5556, 0, 0, 0.478246,-99) , 
4, 11.3, 0, 0, 0.559508,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.266396);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.975337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49552,-99) , 
5, 46.4444, 1, 0, 0.746292,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398208,-99) , 
6, 4.44444, 0, 0, 0.428518,-99) , 
5, 82.7778, 1, 0, 0.468343,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.314965);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 4.01111, 1, 0, 0.63477,-99) , 
NN(
0, 
0, 
-1, 228.333, 1, -1, 0.412101,-99) , 
0, 69.5556, 1, 0, 0.55057,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.28127);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476694,-99) , 
3, 9.73333, 0, 0, 0.612344,-99) , 
NN(
0, 
0, 
-1, 12.4778, 1, -1, 0.205082,-99) , 
6, 4.08889, 1, 0, 0.591681,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.219426);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.73333, 1, 1, 0.596927,-99) , 
NN(
0, 
0, 
-1, 11.4222, 1, -1, 0.20139,-99) , 
6, 4.08889, 1, 0, 0.575238,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.263879);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440533,-99) , 
3, 11.3333, 1, 0, 0.571693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.114935,-99) , 
7, 22.8333, 1, 0, 0.552093,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.253814);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.84252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488723,-99) , 
7, 17.0667, 1, 0, 0.693444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.778095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434482,-99) , 
3, 15.2, 0, 0, 0.47273,-99) , 
3, 9.6, 1, 0, 0.540767,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.234245);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.36667, 0, 1, 0.910478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428778,-99) , 
3, 14.2, 0, 0, 0.474771,-99) , 
4, 17.0333, 0, 0, 0.506758,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.291715);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455839,-99) , 
6, 3.43333, 1, 0, 0.602693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211435,-99) , 
2, 25.2222, 0, 0, 0.354255,-99) , 
5, 298.778, 1, 0, 0.570007,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.188835);
  fForest.push_back( 
NN(
0, 
0, 
-1, 38.6667, 1, 1, 0.593311,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.300607);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325559,-99) , 
3, 7.72222, 0, 0, 0.599701,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0396991,-99) , 
2, 28.8889, 0, 0, 0.33254,-99) , 
3, 14.1667, 1, 0, 0.572568,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.301099);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 21.2222, 0, 1, 0.850314,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332721,-99) , 
4, 7.18889, 0, 0, 0.538554,-99) , 
4, 15.8333, 0, 0, 0.571506,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.321359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.93333, 0, 1, 0.615565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.217894,-99) , 
1, 1.29111, 0, 0, 0.346339,-99) , 
4, 11.4556, 1, 0, 0.528338,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.378474);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.768144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347633,-99) , 
2, 45.5556, 1, 0, 0.728533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333558,-99) , 
6, 2.83333, 1, 0, 0.408479,-99) , 
6, 3.76667, 0, 0, 0.515061,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.331583);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.797034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42782,-99) , 
3, 9.71111, 0, 0, 0.552686,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.20946,-99) , 
0, 65.5556, 0, 0, 0.365591,-99) , 
3, 10.8778, 1, 0, 0.461764,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.485984);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326271,-99) , 
7, 17.6333, 1, 0, 0.60197,-99) , 
NN(
0, 
0, 
-1, 15.4444, 0, -1, 0.265489,-99) , 
4, 11.6111, 0, 0, 0.356707,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.250205);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422073,-99) , 
0, 84.6667, 1, 0, 0.68836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42949,-99) , 
0, 43.3333, 1, 0, 0.459065,-99) , 
0, 80.6667, 0, 0, 0.506807,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.339281);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.78455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392635,-99) , 
2, 18.2222, 0, 0, 0.665064,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388734,-99) , 
4, 6.34444, 1, 0, 0.438101,-99) , 
5, 150.111, 1, 0, 0.521399,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.252375);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.954233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469326,-99) , 
6, 4.37778, 1, 0, 0.810824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421602,-99) , 
1, 3.35667, 0, 0, 0.453218,-99) , 
6, 4.24444, 0, 0, 0.49956,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.354024);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202284,-99) , 
6, 3.8, 1, 0, 0.60019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.301674,-99) , 
6, 3.11111, 0, 0, 0.413946,-99) , 
5, 181, 0, 0, 0.509657,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.35863);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.808853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496077,-99) , 
3, 9.73333, 1, 0, 0.628266,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.68416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.142238,-99) , 
4, 11.9333, 0, 0, 0.296779,-99) , 
2, 14.3333, 0, 0, 0.554193,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.34209);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.791765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.127537,-99) , 
7, 14.5889, 0, 0, 0.685594,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.178674,-99) , 
3, 13.8667, 1, 0, 0.477654,-99) , 
2, 29.6667, 0, 0, 0.565,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.377052);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286677,-99) , 
1, 2.75333, 1, 0, 0.661742,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361731,-99) , 
0, 61.2222, 1, 0, 0.460079,-99) , 
4, 8.06667, 0, 0, 0.578305,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.259003);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.67778, 0, 1, 0.849863,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.965357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416957,-99) , 
2, 65.1111, 0, 0, 0.443675,-99) , 
7, 20.8111, 0, 0, 0.484608,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.175575);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 20.9444, 0, 1, 0.550037,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167486,-99) , 
2, 29.1111, 0, 0, 0.33329,-99) , 
0, 77.4444, 1, 0, 0.515662,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.405928);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379248,-99) , 
5, 196, 1, 0, 0.582565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.771995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2947,-99) , 
6, 2.34444, 1, 0, 0.325469,-99) , 
3, 10.1667, 1, 0, 0.455908,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.29537);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391831,-99) , 
6, 3.38889, 1, 0, 0.547484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0419982,-99) , 
7, 13.0333, 1, 0, 0.207132,-99) , 
6, 3.93333, 1, 0, 0.503291,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.235128);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 19.0333, 0, 1, 0.599888,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378747,-99) , 
6, 4.43333, 0, 0, 0.427913,-99) , 
6, 3.26667, 1, 0, 0.521226,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.303597);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.22788,-99) , 
5, 76.2222, 0, 0, 0.529455,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.113273,-99) , 
2, 25.6667, 0, 0, 0.297677,-99) , 
0, 74.6667, 1, 0, 0.472628,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.377526);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370136,-99) , 
3, 11.3556, 0, 0, 0.457628,-99) , 
NN(
0, 
0, 
-1, 3.93333, 1, -1, 0.249785,-99) , 
0, 70.4444, 1, 0, 0.376964,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.435202);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.791467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327095,-99) , 
5, 299.889, 1, 0, 0.727675,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.70594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330035,-99) , 
6, 3.93333, 0, 0, 0.409156,-99) , 
3, 8.7, 1, 0, 0.498187,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.284516);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477188,-99) , 
3, 11.8889, 1, 0, 0.613273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 6.46778, 1, 0, 0.592391,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.463892);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.17794,-99) , 
7, 14.6556, 0, 0, 0.631484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.26782,-99) , 
4, 15.1778, 0, 0, 0.337233,-99) , 
4, 8.24444, 1, 0, 0.47074,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.285298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 237.222, 0, 1, 0.656796,-99) , 
NN(
0, 
0, 
-1, 369.667, 1, -1, 0.38923,-99) , 
3, 10, 0, 0, 0.552767,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.287657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.243917,-99) , 
5, 84.7778, 0, 0, 0.567741,-99) , 
NN(
0, 
0, 
-1, 21.4444, 0, -1, 0.146764,-99) , 
7, 19.8556, 1, 0, 0.523762,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.327698);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 50.4444, 1, 1, 0.621659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.918895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346453,-99) , 
0, 47.6667, 1, 0, 0.400501,-99) , 
5, 150.667, 1, 0, 0.479636,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.301127);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412947,-99) , 
0, 67.3333, 1, 0, 0.579743,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351837,-99) , 
5, 88.3333, 1, 0, 0.417077,-99) , 
3, 11.6333, 0, 0, 0.485553,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.356381);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.676156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334039,-99) , 
0, 67.6667, 1, 0, 0.561384,-99) , 
NN(
0, 
0, 
-1, 69.4444, 0, -1, 0.330506,-99) , 
3, 10.2333, 1, 0, 0.438549,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.173205);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.787592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488646,-99) , 
4, 16.1444, 0, 0, 0.529018,-99) , 
NN(
0, 
0, 
-1, 10.4333, 1, -1, 0.113354,-99) , 
6, 4.05556, 1, 0, 0.483408,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.352544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.780254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463212,-99) , 
5, 181, 0, 0, 0.677491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311063,-99) , 
6, 3.15556, 1, 0, 0.412583,-99) , 
4, 11.3, 0, 0, 0.525671,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.278016);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 191, 1, 1, 0.706182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390079,-99) , 
7, 18.4333, 0, 0, 0.431141,-99) , 
6, 2.76667, 1, 0, 0.484618,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.309365);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 260.667, 0, 1, 0.671774,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380446,-99) , 
2, 10, 1, 0, 0.435679,-99) , 
2, 24.7778, 0, 0, 0.525019,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.188952);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419914,-99) , 
3, 12.8778, 1, 0, 0.555263,-99) , 
0, 38.6667, 1, 0, 0.56692,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.300312);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.806037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442236,-99) , 
4, 13.5667, 1, 0, 0.743562,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0921906,-99) , 
6, 3.86667, 1, 0, 0.464797,-99) , 
3, 8.67778, 1, 0, 0.533904,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.329575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347886,-99) , 
3, 8.47778, 0, 0, 0.517463,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.811506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0585035,-99) , 
0, 78, 0, 0, 0.236659,-99) , 
7, 13.8778, 0, 0, 0.469673,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.380046);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.835581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455309,-99) , 
3, 13.8667, 0, 0, 0.529136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.793248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242148,-99) , 
5, 26.1111, 1, 0, 0.277144,-99) , 
5, 179.667, 0, 0, 0.401964,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.151871);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.749781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489184,-99) , 
6, 2.76667, 1, 0, 0.530073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.098125,-99) , 
5, 476.333, 1, 0, 0.497031,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.117567);
  fForest.push_back( 
NN(
0, 
0, 
-1, 47.6667, 1, 1, 0.558514,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.359901);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.691774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397386,-99) , 
4, 8.3, 0, 0, 0.596513,-99) , 
NN(
0, 
0, 
-1, 12.0778, 0, -1, 0.320278,-99) , 
3, 10.2333, 1, 0, 0.437988,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.115708);
  fForest.push_back( 
NN(
0, 
0, 
-1, 36.2222, 1, 1, 0.557597,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.329584);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.04444, 1, 1, 0.810601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350822,-99) , 
0, 75.6667, 0, 0, 0.426167,-99) , 
0, 51, 1, 0, 0.459663,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.279032);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 12.3444, 0, 1, 0.598209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247315,-99) , 
6, 2.33333, 1, 0, 0.345179,-99) , 
1, 1.40444, 1, 0, 0.546967,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.331465);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0923983,-99) , 
0, 92.4444, 1, 0, 0.622334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.246781,-99) , 
5, 448, 1, 0, 0.58779,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.240926);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998098,-99) , 
NN(
0, 
0, 
-1, 9.83333, 0, -1, 0.401332,-99) , 
2, 77, 0, 0, 0.430492,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.219347);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 60.4444, 1, 1, 0.628476,-99) , 
NN(
0, 
0, 
-1, 3.76667, 1, -1, 0.402678,-99) , 
5, 147.556, 1, 0, 0.479693,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.349018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 46.2222, 1, 1, 0.869268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360539,-99) , 
5, 75.2222, 0, 0, 0.601526,-99) , 
0, 54.3333, 1, 0, 0.637803,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.41739);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.998475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496613,-99) , 
6, 3.15556, 1, 0, 0.706013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289536,-99) , 
3, 8.53333, 1, 0, 0.348337,-99) , 
2, 35.3333, 0, 0, 0.433224,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.228527);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.967532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434933,-99) , 
7, 17.8667, 1, 0, 0.824284,-99) , 
NN(
0, 
0, 
-1, 15.0222, 0, -1, 0.413348,-99) , 
5, 72.1111, 1, 0, 0.452031,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.25294);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.16753,-99) , 
7, 22.1444, 1, 0, 0.576129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.067349,-99) , 
1, 4.94, 1, 0, 0.550941,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.220179);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.971142,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376832,-99) , 
6, 3.26667, 0, 0, 0.476114,-99) , 
3, 16.3889, 0, 0, 0.493497,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.204341);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.63333, 1, 1, 0.566846,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0764305,-99) , 
0, 68.5556, 1, 0, 0.32019,-99) , 
7, 14.1444, 0, 0, 0.51393,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.169277);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 17.2333, 0, 1, 0.545575,-99) , 
NN(
0, 
0, 
-1, 13.9333, 0, -1, 0.106069,-99) , 
6, 4.05556, 1, 0, 0.497299,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.302461);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 18.0222, 0, 1, 0.634937,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367149,-99) , 
4, 4, 1, 0, 0.423042,-99) , 
4, 11.4556, 0, 0, 0.49253,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.204353);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 9.31111, 0, 1, 0.640931,-99) , 
NN(
0, 
0, 
-1, 3.86667, 1, -1, 0.412331,-99) , 
7, 18.1667, 0, 0, 0.468593,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.31534);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365682,-99) , 
6, 3.54444, 1, 0, 0.546924,-99) , 
NN(
0, 
0, 
-1, 39.6667, 0, -1, 0.205359,-99) , 
4, 12.5, 1, 0, 0.482028,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.284048);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 9, 0, 1, 0.788237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340664,-99) , 
5, 221.667, 1, 0, 0.453887,-99) , 
4, 15.9889, 0, 0, 0.523955,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.3418);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.801778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394489,-99) , 
4, 9.3, 1, 0, 0.610945,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358649,-99) , 
1, 1.40444, 0, 0, 0.428659,-99) , 
5, 228.333, 0, 0, 0.507289,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.297182);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.26667, 0, 1, 0.858273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382942,-99) , 
5, 274.889, 0, 0, 0.443592,-99) , 
0, 49.6667, 1, 0, 0.482708,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.341579);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 50.1111, 0, 1, 0.788776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.767783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400103,-99) , 
1, 2.54556, 0, 0, 0.458519,-99) , 
0, 54.3333, 1, 0, 0.535629,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.269086);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 75, 0, 1, 0.607574,-99) , 
NN(
0, 
0, 
-1, 10.0667, 0, -1, 0.0709853,-99) , 
0, 83, 1, 0, 0.567821,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.284731);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.863978,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367214,-99) , 
6, 2.87778, 1, 0, 0.433172,-99) , 
0, 49.6667, 1, 0, 0.461653,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.335705);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376207,-99) , 
5, 242.778, 1, 0, 0.594325,-99) , 
NN(
0, 
0, 
-1, 10.3, 1, -1, 0.320491,-99) , 
2, 15.3333, 0, 0, 0.517788,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.29828);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414181,-99) , 
4, 9.68889, 0, 0, 0.525877,-99) , 
NN(
0, 
0, 
-1, 19.5667, 1, -1, 0.23657,-99) , 
0, 75.6667, 1, 0, 0.465272,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.24862);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.41556, 0, 1, 0.602989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0686604,-99) , 
7, 15.1667, 0, 0, 0.333035,-99) , 
6, 3.86667, 1, 0, 0.56279,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.425777);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.713785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224479,-99) , 
7, 16.9667, 1, 0, 0.629729,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.312328,-99) , 
3, 13.8333, 0, 0, 0.373889,-99) , 
2, 15.3333, 1, 0, 0.469519,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.451981);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306604,-99) , 
4, 7.65556, 0, 0, 0.553949,-99) , 
NN(
0, 
0, 
-1, 6.33333, 1, -1, 0.11622,-99) , 
3, 7.22222, 0, 0, 0.479289,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.473055);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 183, 1, 1, 0.818164,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.180331,-99) , 
6, 3.32222, 1, 0, 0.37003,-99) , 
0, 55.8889, 1, 0, 0.477998,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.400996);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.683367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40273,-99) , 
4, 7, 0, 0, 0.532817,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205021,-99) , 
0, 59.5556, 1, 0, 0.298275,-99) , 
4, 8.83333, 1, 0, 0.419399,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.300174);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306732,-99) , 
7, 16.9111, 1, 0, 0.449115,-99) , 
NN(
0, 
0, 
-1, 57.6667, 1, -1, 0.247204,-99) , 
6, 3.54444, 1, 0, 0.381504,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.325197);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 20.3333, 0, 1, 0.855554,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305682,-99) , 
3, 9.93333, 1, 0, 0.404303,-99) , 
5, 354.333, 0, 0, 0.460949,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.340846);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416318,-99) , 
5, 153.222, 0, 0, 0.482916,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211607,-99) , 
7, 13.6444, 1, 0, 0.26385,-99) , 
5, 196, 1, 0, 0.385534,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.255367);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.890734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294924,-99) , 
0, 65.4444, 0, 0, 0.755671,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396002,-99) , 
7, 15.0333, 0, 0, 0.512149,-99) , 
7, 12.9889, 1, 0, 0.545995,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.125624);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.70667, 0, 1, 0.546434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0100032,-99) , 
1, 8.06222, 1, 0, 0.527024,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.207444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.889642,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422101,-99) , 
7, 13.3111, 1, 0, 0.445736,-99) , 
0, 45.3333, 1, 0, 0.466723,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.27145);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 7.25556, 0, 1, 0.707455,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283971,-99) , 
5, 179.667, 0, 0, 0.420724,-99) , 
6, 2.78889, 1, 0, 0.462812,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.3365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.939605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.256294,-99) , 
1, 0.756667, 0, 0, 0.809202,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.737934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405662,-99) , 
1, 3.69333, 0, 0, 0.436635,-99) , 
5, 64.5556, 1, 0, 0.505521,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.183782);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460935,-99) , 
5, 179.667, 1, 0, 0.538313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 15.5444, 1, 0, 0.521339,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.444526);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.692567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298424,-99) , 
2, 40.6667, 1, 0, 0.651032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.219527,-99) , 
2, 17.8889, 1, 0, 0.291455,-99) , 
4, 11.3333, 1, 0, 0.534066,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.185033);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.991428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297646,-99) , 
5, 204, 1, 0, 0.437775,-99) , 
2, 90.8889, 0, 0, 0.459075,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.160103);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.811207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463186,-99) , 
4, 17.1667, 0, 0, 0.491068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 15.3333, 1, 0, 0.468165,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.251657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397123,-99) , 
3, 11.4111, 1, 0, 0.530534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.02486,-99) , 
2, 24.4444, 0, 0, 0.247151,-99) , 
5, 87.4444, 0, 0, 0.49374,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.254872);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465576,-99) , 
3, 14.0333, 0, 0, 0.503399,-99) , 
NN(
0, 
0, 
-1, 25.6667, 0, -1, 0.304315,-99) , 
7, 15.7556, 1, 0, 0.409365,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.301523);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345237,-99) , 
5, 293.222, 1, 0, 0.575117,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.965593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297219,-99) , 
5, 129.889, 1, 0, 0.404444,-99) , 
3, 12.7556, 1, 0, 0.544723,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.336538);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 11.9, 0, 1, 0.657338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205965,-99) , 
1, 1.09111, 1, 0, 0.400293,-99) , 
3, 8.65556, 0, 0, 0.59306,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.110036);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.86482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490102,-99) , 
5, 55.1111, 1, 0, 0.523438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0770045,-99) , 
5, 387.333, 1, 0, 0.507847,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.342283);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 14.9111, 1, 0, 0.604723,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375007,-99) , 
0, 51.3333, 1, 0, 0.406596,-99) , 
3, 12.6, 0, 0, 0.457611,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.315283);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353335,-99) , 
7, 15.7556, 1, 0, 0.489315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.221875,-99) , 
2, 25.3333, 0, 0, 0.297876,-99) , 
4, 7.88889, 0, 0, 0.434587,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.214275);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446916,-99) , 
5, 71.8889, 1, 0, 0.486546,-99) , 
NN(
0, 
0, 
-1, 11.9889, 0, -1, 0.113698,-99) , 
0, 84, 1, 0, 0.452946,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.439299);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.75839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465364,-99) , 
5, 139, 0, 0, 0.671145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.259122,-99) , 
7, 17, 0, 0, 0.374169,-99) , 
0, 64.4444, 0, 0, 0.52382,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
